version: '3'

services:
  api:
    build: api
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    build: db
    ports:
      - "27018:27018"
    volumes:
      - .data:/data